### PR TITLE
resolver stats

### PR DESCRIPTION
**Pull request by ravlio**
collect performance stats of resolvers

### CODE REVIEW

**Review by Mzack9999 — CHANGES_REQUESTED** [review]
minor lint errors

**Comment by calab33p** [comment]
Hi @ravlio , @Mzack9999 , what is the status of this? Is it just lint errors? Happy to jump in and help get this pushed if that would help. I could use this functionality as well.

**Comment by calab33p** [comment]
I also think we could use an error type for possible net.OpError's . I have seen i/o timeouts and conn refused on read.

**Comment by ravlio** [comment]
@calab33p hi. I think this PR is obsolete. I'll close it

**Comment by calab33p** [comment]
@ravlio It's functionality I would find helpful to date. The list of resolvers I'm getting from dnsvalidator.py aren't the best and having some heuristics around which resolvers are good and which ones aren't is something I would find helpful. Is there a reason you think it is obsolete now? Is there something I am missing?

**Pull request closed without merging**
